set dotenv-load := false

default:
    just --list

check:
    cargo check

build:
    cargo build

release:
    cargo build --release

release-small:
    cargo build --profile release-small

fmt:
    cargo fmt

fmt-check:
    cargo fmt --check

clippy:
    cargo clippy --all-targets -- -D warnings

run *args:
    cargo run -- {{args}}

run-client *args:
    cargo run -- --client {{args}}
    
run-server *args:
    cargo run -- --server

run-release *args:
    cargo run --release -- {{args}}

test:
    cargo run -- ../tests/baboon.png

clean:
    cargo clean

