[package]
name = "zv-viewer"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "zv"
path = "src/main.rs"

[dependencies]
anyhow = "1"
arboard = "3.6"
bytemuck = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
eframe = { version = "0.33", features = ["default_fonts", "wgpu", "x11", "wayland"] }
egui = "0.33"
egui_extras = "0.33"
egui-phosphor = { version = "0.11", default-features = false, features = ["regular"] }
image = { version = "0.25", default-features = false, features = ["bmp", "gif", "jpeg", "png", "pnm", "tga", "tiff"] }
rmp-serde = "1"
serde = { version = "1", features = ["derive"] }
serde_bytes = "0.11"
rfd = "0.15"
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
turbojpeg = "1.5"

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.23"
objc2-app-kit = { version = "0.2.2", features = ["NSScreen", "NSView", "NSWindow"] }
raw-window-handle = "0.6"
