[package]
name = "zv-viewer"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
eframe = { version = "0.33", features = ["wgpu"] }
egui = "0.33"
image = { version = "0.25", default-features = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
